In [1]:
# 1번 : creation
import numpy as np
L = [1, 2, 3, 4, 5]
np.array(L)

array([1, 2, 3, 4, 5])

In [6]:
# 2번 : creation (2)
np.full((1,10),0)
#np.zeros(10)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
# 3번 : creation (3)
L = [1.1, 2.2, 3.3, -4.4, 5.5]
np.array(L).astype('float32')
#np.array(L, dtype='f')

array([ 1.1,  2.2,  3.3, -4.4,  5.5], dtype=float32)

In [16]:
# 4번 : creation (4)
np.arange(1,1001)

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

In [18]:
# 5번 : creation (5)
np.arange(0.0,1.1,step= 0.1)

array([0.])

In [36]:
# 6번 : array data type
bool,
int8,int16,int32,int64,
uint8,uint16,uint32,uint64,
float16,float32,float64,
complex64,complex128,
string_

array(b'3', dtype='|S11')

In [ ]:
# 7번 : array data type (2)
numpy는 수치계산에 특화된 라이브러리입니다.
대부분의 수치 계산에 사용되는 데이터는 벡터(vector)이고, 이 벡터를 표현한게 numpy array입니다.
벡터의 원소들은 기본적으로 정해진 vectro space에 표현됩니다. 이 vector space를 정의하면 나타나는 숫자의 표현 범위도 정해집니다.

정해진 표현 범위에서 효율적인 연산을 하기 위해서는 data type이 통일될 필요가 있습니다.
data type이 통일되면 operator를 이용한 연산을 할 때, type checking할 필요가 없어지면서 시간상 이득이 있습니다.
이를 효과적으로 이용한 것이 바로 Numpy가 제공하는 Universal Function이나 Broadcasting입니다.

python과 numpy 연산자 비교를 해보면 methods, attributes에서는 NumPy가 훨씬 많음(Python int는 8개 NumPy int64는 68개로 약 8배 차이)

In [38]:
# 8번 : indexing
arr = np.array([31, 24, 37, 14, 25])
arr[1]

24

In [55]:
# 9번 : indexing (2)
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2[1,-1]
#arr2[1][2]

6

In [61]:
# 10번 : fancy indexing
arr2 = np.array([ [10, 9, 8], [7, 6, 5], [4, 3, 2] ])
arr2[0]
arr2[1]

array([7, 6, 5])

In [66]:
# 11번 : array masking
arr = np.array([30, 4, 550, 9, 112, 10000, 15, 21])
arr[arr > 30]

array([  550,   112, 10000])

In [72]:
# 12번 : max min
arr = np.array([50, 1110, 1, 230, 3, 40, 517590, -41, -4959])
print('min :', np.min(arr))
print('max :', np.max(arr))
                      
#print(f"min : {arr.min()}")
#print(f"max : {arr.max()}")                     

min : -4959
max : 517590


In [79]:
# 13번 : max min indexing
arr = np.array([1, 33, 5502, 221, -591, 0, -9, 50491])
print('index of min : ',arr.argmin())
print('index of max : ',arr.argmax())

#print(f"index of min : {arr.argmin()}")
#print(f"index of max : {arr.argmax()}")

index of min :  4
index of max :  7


In [83]:
# 14번 : concat

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9])
np.concatenate((arr1,arr2))
#np.concatenate([arr1, arr2])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
# 15번 : concat (2)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

np.vstack([arr1,arr2,arr3])

#np.stack((arr1, arr2, arr3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
# 16번 : vector
v1 = np.array([1, 2, 3])
v2 = np.array([4, -1, 2])

v1+v2

array([5, 1, 5])

In [94]:
# 17번 : vector (2)
v1 = np.array([1, 2, 3])
v2 = np.array([4, -1, 2])
np.dot(v1,v2)

8

In [95]:
# 18번 : broadcasting
arr1 = np.array([1, 2, 3])

arr1+3

array([4, 5, 6])

In [96]:
# 19번 : broadcasting (2)
mat1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
v1 = np.array([-1, -2, -3])

mat1 + v1

array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6]])

In [101]:
# 20번 : reshaping
img = np.random.random((5, 5))
img.reshape(-1)
img.flatten()

array([0.34665433, 0.98679477, 0.52349974, 0.50666822, 0.25695883,
       0.28437298, 0.09871967, 0.61011825, 0.58507634, 0.74327577,
       0.17630537, 0.89593429, 0.97582839, 0.53053579, 0.74628991,
       0.94880551, 0.88854597, 0.41461017, 0.49864185, 0.18299634,
       0.92882291, 0.39859353, 0.63969906, 0.25337545, 0.45379801])

In [102]:
# 21번 : reshaping (2)
N = int(input("N? : ")) # 사용자 입력으로 받은 자연수 N
data = np.random.random((N, 6)) # N x 6 matrix
data.flatten()

N? : 3


array([0.49716924, 0.58459145, 0.92561771, 0.75297061, 0.2037405 ,
       0.33214485, 0.31672676, 0.55949337, 0.10038488, 0.55920771,
       0.22486375, 0.44246605, 0.97929065, 0.17894895, 0.77045071,
       0.68710052, 0.59387486, 0.08412667])

In [107]:
# 22번 : math function
x = 10
print('sin(10):',np.sin(x))
print('cos(10): ',np.cos(x))
print('tan(10): ',np.tan(x))

#print(f"sin(10) : {np.sin(10):.4f}")
#print(f"cos(10) : {np.cos(10):.4f}")
#print(f"tan(10) : {np.tan(10):.4f}")

sin(10): -0.5440211108893698
cos(10):  -0.8390715290764524
tan(10):  0.6483608274590866


In [110]:
# 23번 : math function (2)

# x = float(input("Number? : "))
x = 3.14
print(f"abs(10) : {np.abs(x):.4f}")
print(f"root(10) : {np.sqrt(x):.4f}")
print(f"square(10) : {np.square(x):.4f}")

abs(10) : 3.1400
root(10) : 1.7720
square(10) : 9.8596


In [112]:
# 24번 : math function (3)
#x = np.abs(float(input("Number? : ")))
x = 3.14
print(f"exp(3,14) : {np.exp(x):.4f}")
print(f"log(3.14) : {np.log(x):.4f}")

exp(3,14) : 23.1039
log(3.14) : 1.1442


In [119]:
# 25번 : sorting
arr = np.array([1, -5, 3.4, 55.41, -1009, 2245, -575, -1935.124])
np.sort(arr)

array([-1.935124e+03, -1.009000e+03, -5.750000e+02, -5.000000e+00,
        1.000000e+00,  3.400000e+00,  5.541000e+01,  2.245000e+03])

In [140]:
# 26번 : sorting (2)
arr = np.array([1, -5, 3.4, 55.41, -1009, 2245, -575, -1935.124])
s = arr.argsort()
#new_s = arr[s]
print(arr.argsort())
#print(arr[s])

#np.argsort(arr)

[7 4 6 1 0 2 3 5]


In [169]:
# 27번 : sorting (3)
mat = np.array([[1, -1, 3],
               [4, 3, -6],
               [0, 11, 9]])
np.sort(mat)

array([[-1,  1,  3],
       [-6,  3,  4],
       [ 0,  9, 11]])

In [167]:
# 28번 : sorting (4)
mat = np.array([[1, -1, 3],
               [4, 3, -6],
               [0, 11, 9]])
np.sort(mat, axis=0)[::-1]

array([[ 4, 11,  9],
       [ 1,  3,  3],
       [ 0, -1, -6]])