In [ ]:
# 1번: Machine Learning Workflow
#
독립적인 단계를 통해 여러 데이터 과학자가 과도 한 처리 시간이 소모 계산 리소스 없이 동시에 동일한 파이프라인에서 작업할 수 있습니다. 또한 별도의 단계를 통해 각 단계에 서로 다른 계산 형식/크기를 쉽게 사용할 수 있는 장점
#
업무를 step by step으로 진행할 수 있으며, 그 과정에서 효율적인 시스템을 만들 수 있다.

예를들어 workflow를 무시하고, pipeline부터 만들다보면 데이터의 형식이나 크기에 맞지않는 비효율적인 시스템이 나올 수 도 있으며,

전처리과정에 따라 변화할 수 있는 여지들이 있음에도 불구하고 무작정 프로그램만 만들다보면 훨씬 비효율적인 시스템으로 만들어질 수 있음.

때문에 업무의 효율성 뿐만아니라 시스템의 성능 측면에서도 workflow 를 만들고 가져가는 것이 필요하다고 생각됨.


In [ ]:
# 2번: Iris 생태계 연구
# 잠시 생태계를 연구하는 학자가 되어봅시다. Iris(붓꽃) 종의 생태를 연구하기 위해 Iris 종과 관련된 데이터를 수집하려고 합니다.
# Iris의 종의 분류와 관련된 정리된 데이터셋이 있는지 찾아보고, 없을 경우엔 어떻게 데이터를 얻을 수 있을지 작성해보세요.

scikit-learn의 datasets 모듈에 포함되어 있습니다. load_iris 함수를 사용해서 데이터를 적재

In [ ]:
# 3번 : Iris dataset
# Iris 종 분류를 위한 데이터를 이미 수집하여 만들어 놓은 사례가 있습니다.
# 1936년 Ronald Fisher의 논문 "The use of multiple measurements in taxonomic problems" 에서 Iris 종 분류를 위한 데이터가 처음 소개가 되었습니다.
# Iris dataset이 어떤 목적으로 수집되어 만들어졌는지 조사한 내용을 정리해보세요.
 붓꽃의 꽃잎petal과 꽃받침sepal의 폭과 길이를 센티미터 단위로 측정하여 들꽃에 있는 붓꽃의 품종을 구분하기 위해서 


In [ ]:
# 4번: Source the Iris dataset
# Iris dataset을 얻을 수 있는 경로에는 크게 3가지가 있습니다.
sklearn안에있는데 datasets를 통해서 편하게 불러올 수 있다. 이에 비해 kaggle이나 UCI는 데이터 파일을 다운받아야한다

In [6]:
# 5번 : sklearn.load_iris
#코드 구현의 편의성을 위해 scikit-learn에서 Iris dataset을 불러와서 사용하겠습니다.
#sklearn.datasets.load_iris() 를 통해 데이터를 DataFrame으로 가져와 출력하는 코드를 작성하세요.
from sklearn.datasets import load_iris
import pandas as pd 
# iris dataset을 DataFrame으로 불러오는 코드
iris = load_iris()
df = iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['target'] = iris.target
df

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                  5.1               3.5  ...               0.2       0
1                  4.9               3.0  ...               0.2       0
2                  4.7               3.2  ...               0.2       0
3                  4.6               3.1  ...               0.2       0
4                  5.0               3.6  ...               0.2       0
..                 ...               ...  ...               ...     ...
145                6.7               3.0  ...               2.3       2
146                6.3               2.5  ...               1.9       2
147                6.5               3.0  ...               2.0       2
148                6.2               3.4  ...               2.3       2
149                5.9               3.0  ...               1.8       2

[150 rows x 5 columns]

In [8]:
iris = pd.DataFrame(load_iris().data, columns=load_iris().feature_names)
iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [10]:
# 6번 : Estimate the model
# 데이터를 얻었으니, 우선 모델을 통해 평가를 해봅니다.
# Iris 종을 파악하기 위한 알맞는 모델을 선정한 뒤, 그 이유를 짧게 주석으로 작성해보세요.
# 선택한 estimator를 sklearn을 사용하여 코드로 작성한 뒤, 간단한 성능 평가도 함께해보세요.
# 선정한 estimator 불러오기
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Iris dataset 불러오기
X, y = load_iris(return_X_y=True)
 # training / test 데이터 세팅
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
# 불러온 estimator 객체 생성
clf = LogisticRegression()
clf.fit(X_train, y_train)

# estimator train, test and evaluate.
clf.score(X_test, y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9666666666666667

In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
# Iris dataset 불러오기
X, y = load_iris(return_X_y=True)
 # training / test 데이터 세팅
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
# 불러온 estimator 객체 생성
clf = RandomForestClassifier()
# estimator train, test and evaluate.
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_pred, y_test)

In [ ]:
# 7번 : check estimator
#선택한 estimator를 통해 Iris dataset을 분류했을 때의 성능은 충분한가요?
#만약 분류 모델의 달성 목표가 정확도 기준으로 0.95였다면, 목표를 달성하였나요?
#그렇지 못했다면, 정확도를 올리기 위해 개선해야 할 포인트를 찾아서 작성해보세요.

LogisticRegression을 기준으로 정확도가 96%로 기준을 만족하였다. 추가적인 파라미터 튜닝을 통해서 정확도를 올릴 수 있을 것이다

Ridge나 Lasso Regression을 통하여 모델을 학습해본다. 각각의 alpha 값을 데이터셋에 맞게끔 grid search를 진행하여 본다.



In [ ]:
# 8번 : iris pre-processing 1
#머신러닝에서 데이터는 feature vector로 표현이 되어 학습 및 평가에 사용됩니다.
#feature vector로 표현이 될 때, 어떤 feature를 어떻게 사용할지에 대해서 정하는 과정을 feature engineering이라고 합니다.
#대표적인 feature engineering 방법에 Normalization과 Standardization 있습니다.
#아래 3문항에 대한 답변을 적어주세요.
#① Iris dataset의 각 4개의 Feature의 의미와 특징에 대해서 서술하세요.
#② Iris dataset을 normalization을 수행했을 때와 안했을 때의 차이에 대해 서술하세요. e.g. normalization 전후의 sepal length의 최대/최소값.
#③ Iris dataset을 normalization 했을 때와 standardization을 했을 때의 차이에 대해 서술하세요.

#꽃받침 길이 (cm),꽃받침 폭 (cm),꽃잎 길이 (cm),꽃잎 폭 (cm)
#정규화가 표준화와 다른 가장 큰 특징은 모든 데이터가 0 ~ 1 사이의 값을을 가진다
import matplotlib.pyplot as plt
import seaborn as sns

iris = load_iris()
x = iris['data']
X = x[:, 0]
X_ = (X - X.min()) / (X.max() - X.min())
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
sns.distplot(X, bins=5)
plt.title('Original', fontsize=16)

plt.subplot(1, 2, 2)
sns.distplot(X_, bins=5)
plt.title('Normalization', fontsize=16)
plt.show()


In [ ]:
1. 각각의 꽃에 대하여 꽃받침의 길이와 넓이, 꽃잎의 길이와 넓이이다.

Scaling은 각각의 Xi에 대하여 서로의 단위가 다를 때, 이를 맞춰주기 위하여 진행한다. 예를 들어, 키와 몸무게에 대한 데이터에서 키는 150이상의 데이터가 많은 반면, 몸무게는 100이하의 데이터가 많다. 이러한 경우, 단위를 보다 통일시켜주기위하여 scaling을 진행할 수 있다. 이를 통해 특정 변수에 의해 모델 결과가 크게 변화하는 현상을 방지할 수 있다.

2. 이때 Normalization이란 한 변수의 최소값과 최대값을 0과 1로 두어 scaling해주는 것이다. max_value - x_value / max_value - min_value를 통해 수행한다.

3. Standardization이란 한 변수의 데이터가 표준정규분포의 parameter인 평균 = 0, 분산 = 1이 되도록 변수를 scaling하는 것이다.

이 때, 표준화와 정규화 중 어떤 scaling 방법이 더 좋냐에 대한 답은 없다. 데이터 셋에 맞게끔 둘 다 해보고 더 좋은 성능을 내는 방법을 택하는 것이 좋다.



In [19]:
# 9번 : iris pre-processing 2
# scikit-learn 라이브러리를 사용해 Normalization과 Standardization을 Iris dataset에 적용하는 코드를 작성하세요.

# Min-max scaling, Standard scaling 라이브러리 불러오기
from sklearn.preprocessing import MinMaxScaler,StandardScaler

X, y = load_iris(return_X_y=True)
# X에 min-max scaling을 적용
normalized = MinMaxScaler().fit_transform(X)

# X에 standard scaling을 적용
standardized = StandardScaler().fit_transform(X)

print(normalized)
print(standardized)

[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]
 [0.30555556 0.79166667 0.11864407 0.125     ]
 [0.08333333 0.58333333 0.06779661 0.08333333]
 [0.19444444 0.58333333 0.08474576 0.04166667]
 [0.02777778 0.375      0.06779661 0.04166667]
 [0.16666667 0.45833333 0.08474576 0.        ]
 [0.30555556 0.70833333 0.08474576 0.04166667]
 [0.13888889 0.58333333 0.10169492 0.04166667]
 [0.13888889 0.41666667 0.06779661 0.        ]
 [0.         0.41666667 0.01694915 0.        ]
 [0.41666667 0.83333333 0.03389831 0.04166667]
 [0.38888889 1.         0.08474576 0.125     ]
 [0.30555556 0.79166667 0.05084746 0.125     ]
 [0.22222222 0.625      0.06779661 0.08333333]
 [0.38888889 0.75       0.11864407 0.08333333]
 [0.22222222 0.75       0.08474576 0.08333333]
 [0.30555556 0.58333333 0.11864407 0.04166667]
 [0.22222222 

In [ ]:
# 10번 : data-leakage
# preprocessing 단계에서 다음과 같은 전처리를 수행하였습니다.
# normalized_X = MinmaxScaler.fit_transform(X)
# X_train, X_test, y_train, y_test = train_test_split(normalized_X, y, test_size=0.2)
# 위 코드로 생성된 X_train 데이터를 기준으로 학습을 시킨 뒤, X_test를 테스트하면 어떤 문제가 생기는지 서술해주세요.
테스트 데이터의 특성이 이미 전처리단계에서 스케일링 되었기 때문에 교차검증을 할 수 없다.

머신러닝 문제에서 train set과 test set을 분리할 때, 무조건 test set은 완전히 새롭게 경험할 데이터여야 한다. 그렇지 않고 training 과정에서 test set에 대한 정보가 들어갈 경우, 모델의 일반화 성능을 측정하기 위하여 진행하는 test 단계의 의미가 무색된다.

따라서, 위에 경우에 scaling 하는 경우에 있어서도 X_train, X_test 전부의 데이터를 통해서 scaling을 한 뒤에 나눠주면 안된다. Scaling을 진행하기 이전에 train set과 test set을 나눠준 뒤, train set에 대해서 scaling을 진행해줘야 한다.



In [21]:
# 11번 : Iris building pipeline
# data leakage 문제를 해결하고, preprocessor와 estimator를 하나로 결합해주는 pipeline 구조를 만드는 코드를 작성하세요.
# sklearn에서 pipeline 불러오기
from sklearn.pipeline import make_pipeline
# code from 10번
# 위에서 만든 preprocessor와 estimator을 합치기
pipe = make_pipeline(MinMaxScaler(), LogisticRegression())
pipe.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('minmaxscaler', MinMaxScaler(copy=True, feature_range=(0, 1))),
                ('logisticregression',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_scaling=1,
                                    l1_ratio=None, max_iter=100,
                                    multi_class='auto', n_jobs=None,
                                    penalty='l2', random_state=None,
                                    solver='lbfgs', tol=0.0001, verbose=0,
                                    warm_start=False))],
         verbose=False)

In [25]:
from sklearn.pipeline import Pipeline
pipe = Pipeline([('scaler', MinMaxScaler()), ('classifier', LogisticRegression())])
pipe.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('scaler', MinMaxScaler(copy=True, feature_range=(0, 1))),
                ('classifier',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_scaling=1,
                                    l1_ratio=None, max_iter=100,
                                    multi_class='auto', n_jobs=None,
                                    penalty='l2', random_state=None,
                                    solver='lbfgs', tol=0.0001, verbose=0,
                                    warm_start=False))],
         verbose=False)

In [ ]:
# 12번 : Evaluation Metric - 1
# Iris dataset을 분류하는 문제의 성능을 측정하고자 합니다.
# 분류 문제를 평가하는 방법에는 accuracy, precision 등 여러가지 방법이 있습니다.
# accuracy, precision을 포함하여 분류 문제에서 사용하는 평가 방법을 4가지 이상 찾고, 평가 방법들의 정의와 의미를 정리해보세요.
Accuracy ( 정확도 ) - 전체 데이터 중 올바르게 예측한 비율 - TP + TN / (TP + FN + FP + TN)
Recall ( 재현율 ) - 실제 true 중 예측 true의 비율 - 예측 true / 실제 true = TP / (TP + FN)
precision ( 정밀도 ) - 예측 true 중 실제 true의 비율 - 실제 true / 예측 true = TP / (TP + FP)
F1 Score - 재현율과 정밀도의 조화평균 - 2 *precision*recall / ( precision + recall )

In [ ]:
Precision (정밀도) : 모델이 True라고 분류한 것 중에서 실제 True인 것의 비율
Recall (재현율) : 실제 True인 것 중에서 모델이 True라고 예측한 것의 비율
Accuracy (정확도) : True-True뿐만 아니라 False-False라고 예측한 경우도 고려하는 지표
F1-score : Precision과 Recall의 조화평균

In [37]:
# 13번 : Evaluation Metric - 2
# Iris dataset을 분류하는 문제의 성능을 측정하고자 합니다. 분류 문제의 성능을 측정하는 방법 중에 대표적인 방법인 Accuracy, Precision, Recall, F1-score을 측정하고자 합니다.
# 5A에서 사용했던 코드를 이용하여 각 측정 방법대로 계산한 결과를 출력하는 코드를 작성하세요.
###########################
# Code from 6번

# 선정한 estimator 불러오기
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Iris dataset 불러오기
X, y = X, y = load_iris(return_X_y=True)
 # training / test 데이터 세팅
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
# 불러온 estimator 객체 생성
clf = LogisticRegression()
clf.fit(X_train, y_train)
pred = clf.predict(X_test)

# estimator train, test and evaluate.
############################
# Accuracy, Precision, Recall, F1 score 불러오기
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Accuracy
acc = accuracy_score(y_test, y_pred)
# Precision
pre = precision_score(y_test, y_pred, average=  'weighted')
# Recall
re = recall_score(y_test, y_pred,average=  'weighted')
# F1 score
f1 = f1_score(y_test, y_pred,average=  'weighted')

print("Accuracy : %.3f" % acc)
print("Precision : %.3f" % pre)
print("Recall : %.3f" % re)
print("F1 score : %.3f" % f1)

Accuracy : 0.300
Precision : 0.333
Recall : 0.300
F1 score : 0.310


In [51]:
# 14번 : Model Validation
#학습 데이터셋과 테스트 데이터셋만 2가지로 존재하는 경우에는 동일한 데이터셋에 대해서 계속 학습을 진행하다 보면, 테스트 데이터의 성능을 올리는 방향으로 모델이 과적합 되기 쉽습니다.
#모델의 과적합을 막기 위해서, 테스트 데이터로 평가하기 이전에 평가를 하는 것으로 학습의 성능을 향상시키고 싶습니다.
#학습 데이터의 일부를 validation data로 나누어 학습의 성능을 평가하는 용도로 사용하고자 합니다.
#기존에 작성했던 코드를 활용하여 train data를 나누어 validation data를 만드는 코드를 작성하세요.

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

X, y = load_iris(return_X_y=True)
# train_test_split을 이용하여 X_train, X_val, X_test, y_train, y_val, y_test를 만드는 코드
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_val, X_test, y_val, y_test =  train_test_split(X_train, y_train,test_size=0.25)

print(X_train.shape, X_val.shape, X_test.shape)

(120, 4) (90, 4) (30, 4)


In [52]:
# 15번 : Cross Validation
# train / validation / test의 형태로 데이터를 나누어서 학습을 계속 진행하게 되면, validation data에 학습이 과적합되면서 성능이 제대로 향상되지 않는 문제가 있습니다.
# 이 문제를 해결하기 위해서 학습시에 train/validation로 데이터를 여러 조합으로 나누는 방법이 제시되었습니다.
# 이 방법을 Cross-Validation(CV)이라고 하며, 대표적으로 k-fold Cross Validation을 사용합니다.
# 기존의 작성했던 코드를 활용하여 k-fold cross validation를 통해 학습하는 코드를 작성하세요. (단, k = 5)
# code from 11번

# KFold, Cross validation를 위한 라이브러리 로드.
from sklearn.model_selection import KFold, cross_val_score
# 11번 문제에서 만든 pipeline
clf = pipe
# 5-fold Cross validation을 통해 학습
cv_results =cross_val_score(clf, iris.data, iris.target, cv=5)
# 5-fold CV로 학습한 결과의 평균 정확도 출력
cv_results.mean()


0.9266666666666665

In [53]:
from sklearn.model_selection import KFold, cross_val_score

X, y = load_iris(return_X_y=True)

pipeline = Pipeline([
    ('minmaxscaler',MinMaxScaler()),
    ('logisticregression', LogisticRegression())
])

clf = pipeline
cv_results = cross_val_score(clf, X, y, cv=KFold(n_splits=5))
cv_results.mean()

0.72

In [61]:
# 16번 : Hyper-parameter Tuning - 1
# estimator의 성능 향상을 위해서 hyper-parameter를 조정해봅시다.
# 문제의 예시로 계속 사용했던 LogisticRegression을 예시로 살펴봅시다.
# 굉장히 많은 parameter가 LogisticRegression 모델의 학습에 영향을 끼치지만 그 중에서 C, solver가 학습에 가장 큰 영향을 끼칩니다.
# C를 np.logspace(-4, 4, 4) 로 설정하고, solver는 가능한 모든 solver들("newton-cg", "lbfgs", "liblinear", "sag", "saga") 로 설정합니다.
# 설정한 hyperparameter 조합중 어떤 조합이 가장 좋은지 판단하는 코드를 작성하세요.
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
import numpy as np
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

pipe = Pipeline([
    ('minmaxscaler',MinMaxScaler()),
    ('lr', LogisticRegression())
])


from sklearn.model_selection import GridSearchCV # GridSearchCV 불러오기

clf = pipe

# GridSearch에 사용할 parameter들을 지정한 dictionary
param_grid = {
    'lr__C': np.logspace(-4, 4, 4),
    'lr__solver': ["newton-cg", "lbfgs", "liblinear", "sag", "saga"]
    }

# GridSearchCV를 불러와서 지정한 clf와 param_grid로 설정.
search = GridSearchCV(clf, param_grid)
search.fit(X_train, y_train)
print("Best option from GridSearchCV : ", search.best_params_)



/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the 

Best option from GridSearchCV :  {'lr__C': 10000.0, 'lr__solver': 'newton-cg'}


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the 

In [64]:
# 17번 : Hyper-parameter Tuning - 2
# 모든 조합을 탐색하는 GridSearch와 달리, 주어진 range에서 sampling을 통해 hyper-parameter를 정하는 RandomizedSearch 방법을 사용해봅시다.
# C를 np.logspace(-4, 4, 4) 로 설정하고, solver는 가능한 모든 solver들("newton-cg", "lbfgs", "liblinear", "sag", "saga") 로 설정합니다.
# 설정한 hyperparameter 조합중 어떤 조합이 가장 좋은지 판단하는 코드를 작성하세요.
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
X, y = load_iris(return_X_y=True)

pipe = Pipeline([
    ('minmaxscaler',MinMaxScaler()),
    ('lr', LogisticRegression())
])

# Random SearchCV 불러오기
from sklearn.model_selection import RandomizedSearchCV

clf = pipe

# RandomSearch에 사용할 parameter들을 지정한 dictionary
param_distribution = {
    'lr__C': np.logspace(-4, 4, 4),
    'lr__solver': ["newton-cg", "lbfgs", "liblinear", "sag", "saga"]
}

# Random Search를 불러와서 지정한 clf와 param_grid로 설정.
search2 =RandomizedSearchCV(clf, param_distribution)
# 찾은 best hyperparameter setting을 출력.
search2.fit(X_train, y_train)
print("Best option from RandomizedSearchCV : ", search2.best_params_)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the 

Best option from RandomizedSearchCV :  {'lr__solver': 'lbfgs', 'lr__C': 10000.0}


In [66]:
# 18번 : End-to-End
# 이 때까지 진행했던 모든 코드를 모아서 하나의 완성된 코드를 만들어봅시다.
# Iris dataset이 주어지면 cross-validation을 이용하여 best hyperparameter를 찾고 그 결과를 accuracy, f1-score로 출력하는 코드를 작성하고 최종 성능을 비교하세요.
# 과연 제일 열심히 공부한 사람은 누구일까요?
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
import numpy as np
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

pipe = Pipeline([
    ('minmaxscaler',MinMaxScaler()),
    ('lr', LogisticRegression())
])


from sklearn.model_selection import GridSearchCV # GridSearchCV 불러오기

clf = pipe

# GridSearch에 사용할 parameter들을 지정한 dictionary
param_grid = {
    'lr__C': np.logspace(-4, 4, 4),
    'lr__solver': ["newton-cg", "lbfgs", "liblinear", "sag", "saga"]
    }

# GridSearchCV를 불러와서 지정한 clf와 param_grid로 설정.
search = GridSearchCV(clf, param_grid)
search.fit(X_train, y_train)
print("Best option from GridSearchCV : ", search.best_params_)


model = search.best_estimator_.fit(X_train, y_train)
pred = model.predict(X_test)

# Accuracy
acc = accuracy_score(y_test, y_pred)
# F1 score
f1 = f1_score(y_test, y_pred,average=  'weighted')
print("Accuracy : %.3f" % acc)
print("F1 score : %.3f" % f1)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the 

Best option from GridSearchCV :  {'lr__C': 10000.0, 'lr__solver': 'newton-cg'}
Accuracy : 0.367
F1 score : 0.363


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the 

In [67]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score, f1_score


# Iris dataset 불러오기
X, y = load_iris(return_X_y=True)


# train, test 8:2 split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


# pipeline 정의
pipeline = Pipeline([
    ('minmaxscaler', MinMaxScaler()),
    ('logisticregression', LogisticRegression())
])


clf = pipeline


# clf.get_params().keys(): 모델 파라미터 확인
# search할 파라미터 및 값 정의
param_dist = {
    'logisticregression__C': np.logspace(-4, 4, 4),
    'logisticregression__solver': ["newton-cg", "lbfgs", "liblinear", "sag", "saga"]
}


search = RandomizedSearchCV(clf, param_dist, cv = 5)
search.fit(X_train, y_train)


# random search를 통해 얻은 베스트 파라미터 pipeline
clf = search.best_estimator_
clf.fit(X_train, y_train)


y_pred = clf.predict(X_test)


acc = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average=None).mean()


print("Accuracy : ", acc)
print("F1-score : ", f1)

Accuracy :  1.0
F1-score :  1.0


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the 